apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: payment
    app.kubernetes.io/instance: coolstore-argo
  name: payment
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: payment
    weight: 100
  wildcardPolicy: None