apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: payment
    deploymentconfig: payment
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: payment
    app.kubernetes.io/instance: coolstore-argo
  name: payment
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: payment
    weight: 100
  wildcardPolicy: None