apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argocd
resources:
  - ./support
  - ./main  
  - ./payment
patchesStrategicMerge:
  - cm-patch.yaml
images:
  - name: payment/image
    newName: docker.io/mhildema/payment
    newTag: v1
