# FIXME: The location of the kafka queue should come from a variable
kind: ConfigMap
apiVersion: v1
metadata:
  name: coolstore-topics-cfg
data:
  orders-topic-server: 'my-cluster-kafka-bootstrap.argocd-demo-support:9092'
  payments-topic-server: 'my-cluster-kafka-bootstrap.argocd-demo-support:9092'
  orders-topic-name: 'orders-cfg'
  payments-topic-name: 'payments-cfg'