apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cart
    app.kubernetes.io/instance: coolstore-argo
  managedFields:
  name: cart
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: cart
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: catalog
    app.kubernetes.io/instance: coolstore-argo
  name: catalog
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: catalog
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: coolstore-argo
    project: coolstore-ui
    provider: nodeshift
    version: 1.0.0
  name: coolstore-ui
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: coolstore-ui
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: inventory
    app.kubernetes.io/instance: coolstore-argo
  name: inventory
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: inventory
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: order
    app.kubernetes.io/instance: coolstore-argo
  name: order
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: order
    weight: 100
  wildcardPolicy: None
